### ISSUE TITLE
Support higher API than 31

### ISSUE THREAD

**Issue by ruzko** [roihershberg/bootctl-binary#4]
When trying to install in Lineageos 19 using Magisk 25.0, the installation fails with error:
`Your system API of 32 is greater than the maximum api of 31! Aborting!`

Is this fix as simple as just incrementing the number for supported API version, or are there important changes in slot handling between API versions 31 and 32?

**Comment by roihershberg** [comment]
Very likely that it's as simple as that. I don't know if there are braking changes but from what I know the utility only calls the HAL that is already exists on your device and knows how to switch slots - so there shouldn't be a problem.

**Comment by roihershberg** [comment]
I cannot change it now but you can try to change this line and see if it works: https://github.com/roihershberg/bootctl-binary/blob/master/customize.sh#L15

I would like to hear if it worked.

**Comment by ruzko** [comment]
I'll give it a go and report back what I find. Related, I found this repo with an Android 12 version of just the bootctl sources [https://github.com/capntrips/android_system_extras_bootctl](url)

**Comment by roihershberg** [comment]
Nice!

**Comment by ruzko** [comment]
Alright, I changed the line from '31' to '32', installed it and ran through the seemingly harmless commands.

- hal-info reports `HAL version: android.hardware.boot@1.0::IBootControl`
- get-number-slots reports `3` (Oneplus 6 is A/B, so shouldn't this report 2?)
- get-current-slot reports `1`
- get-suffix 1 reports `_b` (I'm currently booted into the _b slot, so this is correct)
- is-slot-bootable, mark-boot-successful, is-slot-marked-successful all exit without error, which is good.

Next I try `bootctl set-active-boot 0`, and if it works as intended the phone will boot into Linux upon reboot.
....aaaaand It Just Works! [tm]

**Comment by roihershberg** [comment]
Good to hear! Weird that get-number-slots returned 3.

**Comment by ruzko** [comment]
> 

Yea, I tried get-suffix 3 and get-suffix -1 just to see what I could find, but there was nothing. So probably a bug. Bootctl says that slots are 0-based, so would that mean get-number-slots actually reports 4 in natural numbers?

**Comment by roihershberg** [comment]
No I think it only applies to commands like getting the suffix in which you pass the slot as an argument. In the command of the number of slots I think it actually returns the number of slots like you would expect.
