### ISSUE TITLE
Dont work in A13

### ISSUE THREAD

**Issue by seraserboy** [roihershberg/bootctl-binary#5]
API 33 error

**Comment by roihershberg** [comment]
Hi. Does this work?
[bootctl-binary-v2.2.zip](https://github.com/roihershberg/bootctl-binary/files/12210062/bootctl-binary-v2.2.zip)

**Comment by seraserboy** [comment]
Yes, thank you so much installed fine but the APK switch my slot don't work, thanks again.

**Comment by roihershberg** [comment]
Good. Please try to invoke the command yourself with `Termux`.
Run:
```
su
bootctl get-current-slot
```
to get current slot and then
```
bootctl set-active-boot-slot SLOT
```
and SLOT being 0 or 1 and making sure it's the opposite of what you got from `bootctl get-current-slot` (in order to switch the slot).

**Comment by seraserboy** [comment]
![Screenshot_20230731-002411_Terminal](https://github.com/roihershberg/bootctl-binary/assets/40835795/dd6ab111-c8cb-4b5a-80ce-765ec0efc33c)
![Screenshot_20230730-224040_Terminal](https://github.com/roihershberg/bootctl-binary/assets/40835795/2cc4e523-9b1c-46ea-84aa-4665d9108b10)

**Comment by seraserboy** [comment]
![Screenshot_20230731-003044_Termux](https://github.com/roihershberg/bootctl-binary/assets/40835795/6084481a-a99e-41e6-a3a9-722755923fd1)

**Comment by seraserboy** [comment]
![Screenshot_20230731-003229_Termux](https://github.com/roihershberg/bootctl-binary/assets/40835795/1cd42325-150b-4bd0-b350-6ba59712cd6e)

**Comment by roihershberg** [comment]
Please try this:
[bootctl-binary-v2.2.zip](https://github.com/roihershberg/bootctl-binary/files/12212115/bootctl-binary-v2.2.zip)

**Comment by seraserboy** [comment]
Working fine with this version, thank you so much!!!

**Comment by roihershberg** [comment]
Nice!

**Comment by roihershberg** [comment]
I have released the updated version and changed the version code to be actually v2.2.
Can you please try it and check if everything is OK?

**Comment by seraserboy** [comment]
Hi, all is ok, magisk show 2.2 version and can switch slots fine, you are awesome, quick response and quick solution.

**Comment by roihershberg** [comment]
Good! Thank you :)
